# -*- coding: utf-8 -*-
"""MetroBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P3HESYoXOCorqFwN4ozUkkwSVlsbNJJm
"""

# 1. Clean out any corrupted cached versions first
!pip uninstall xformers bitsandbytes unsloth -y

# 2. Install the new, stabilized direct package
!pip install unsloth

# 3. Pull the absolute latest bleeding-edge updates directly from source
!pip install --upgrade --no-cache-dir "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"

# 4. Install supporting structural frameworks
!pip install datasets trl transformers accelerate

import torch
import os
from unsloth import FastLanguageModel
from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

# 1. Base Configuration
max_seq_length = 2048
dtype = None
load_in_4bit = True

# Verification of dataset file
data_path = "/content/metrostack_train.jsonl"
if not os.path.exists(data_path):
    raise FileNotFoundError(f"DATASET MISSING: Please upload '{data_path}' to the Colab file sidebar (folder icon on the left) before running this cell.")

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen2.5-Coder-1.5B-Instruct-bnb-4bit",
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
)

# 2. Setup LoRA Target Parameters
model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 16,
    lora_dropout = 0,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 3407,
    use_rslora = False,
)

# 3. Format & Apply ChatML Templates
from unsloth.chat_templates import get_chat_template
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "qwen-2.5",
)

def formatting_prompts_func(examples):
    convos = examples["messages"]
    texts = [tokenizer.apply_chat_template(convo, tokenize=False, add_generation_prompt=False) for convo in convos]
    return { "text" : texts }

dataset = load_dataset("json", data_files=data_path, split="train")
dataset = dataset.map(formatting_prompts_func, batched = True)

# 4. Define the Fine-Tuning Hyperparameters
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    dataset_num_proc = 2,
    packing = False,
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 60,
        learning_rate = 2e-4,
        fp16 = not torch.cuda.is_bf16_supported(),
        bf16 = torch.cuda.is_bf16_supported(),
        logging_steps = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "outputs",
    ),
)

# 5. Cook the Weights
print("--- STARTING METROBOT TRAINING LOOP ---")
trainer_stats = trainer.train()

# 6. Direct GGUF Extraction
print("--- PACKAGING COMPLETED MODEL TO GGUF ---")
# Ensuring the output format is explicitly defined
model.save_pretrained_gguf("metrobot_gguf", tokenizer, quantization_method = "q4_k_m")
print("--- PIPELINE SUCCESSFUL. YOU CAN NOW DOWNLOAD THE GGUF FILE FROM THE SIDEBAR ---")

# 1. Install compatible dependencies for GGUF conversion
!pip install "protobuf<5.0.0" gguf

# 2. Re-attempt the conversion with robust settings
print("--- RE-ATTEMPTING GGUF CONVERSION ---")
try:
    import os
    os.environ["UNSLOTH_GGUF_USE_FAST"] = "1"

    model.save_pretrained_gguf(
        "metrobot_gguf",
        tokenizer,
        quantization_method = "q4_k_m",
    )
    print("--- CONVERSION FINISHED ---")
    print("The .gguf file should now appear in the 'metrobot_gguf' folder in the left sidebar.")
except Exception as e:
    print(f"Conversion failed again: {e}")
    print("Checking for any generated files:")
    !ls -R metrobot_gguf

from google.colab import drive
drive.mount('/content/drive')

from unsloth import FastLanguageModel
import torch

# 1. Load the base model and tokenizer from the clean hub source
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen2.5-Coder-1.5B-Instruct-bnb-4bit",
    max_seq_length = 2048,
    dtype = None,
    load_in_4bit = True,
)

# 2. Load the fine-tuned adapters from the training output directory
# This ensures we use the correct weights without the corrupted merged config
model = FastLanguageModel.for_inference(model)
model.load_adapter("outputs/checkpoint-60") # Using the final checkpoint

# 3. Configure padding
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# 4. Define the test prompt
messages = [
    {"role": "user", "content": "How do I query the MetroStack database for recent spatial updates?"},
]

# 5. Generate response
inputs = tokenizer.apply_chat_template(
    messages,
    tokenize = True,
    add_generation_prompt = True,
    return_tensors = "pt",
).to("cuda")

outputs = model.generate(
    input_ids = inputs,
    max_new_tokens = 128,
    use_cache = True,
    temperature = 0.7,
    top_p = 0.9,
    repetition_penalty = 1.2
)

response = tokenizer.batch_decode(outputs, skip_special_tokens = True)

print("--- TEST INFERENCE RESPONSE ---")
print(response[0])

"""### Steps to Import into Ollama

1. **Download the GGUF file**: Locate the `.gguf` file in the `/content/metrobot_gguf` folder and download it to your local machine.
2. **Create a Modelfile**: Create a plain text file named `Modelfile` (no extension) in the same folder where you saved the GGUF.
3. **Add the configuration**: Use the content generated below.
4. **Run the Import Command**: Open your terminal and run:
   ```bash
   ollama create metrobot -f Modelfile
   ```
"""

# Helper to print the exact Modelfile content based on your GGUF name
import os

gguf_folder = "/content/metrobot_gguf"
files = [f for f in os.listdir(gguf_folder) if f.endswith(".gguf")]
gguf_filename = files[0] if files else "unsloth.Q4_K_M.gguf"

modelfile_content = f"""FROM ./{gguf_filename}

# Sets the temperature to 0.7 [Higher is more creative, lower is more coherent]
PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER stop <|im_start|>
PARAMETER stop <|im_end|>

# System prompt matches your training
SYSTEM \"\"\"You are Qwen, created by Alibaba Cloud. You are a helpful assistant specialized in MetroStack.\"\"\"
"""

print("--- COPY THIS CONTENT INTO YOUR LOCAL Modelfile ---")
print(modelfile_content)

model.save_pretrained_gguf("/content/metrobot_gguf", tokenizer, quantization_method = "q4_k_m")

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # 1. Move to the root directory and get the conversion tools
# cd /content
# git clone https://github.com/ggerganov/llama.cpp
# cd llama.cpp
# pip install -r requirements.txt
# 
# # 2. Build the quantize tool (this takes a minute or two)
# make quantize
# 
# # 3. Create your output directory
# mkdir -p /content/metrobot_gguf
# 
# # 4. Convert the raw files in /content into an unquantized F16 GGUF
# python convert_hf_to_gguf.py /content --outfile /content/metrobot-f16.gguf --outtype f16
# 
# # 5. Quantize the model to Q4_K_M and output it to your target folder
# ./llama-quantize /content/metrobot-f16.gguf /content/metrobot_gguf/metrobot-Q4_K_M.gguf q4_k_m
# 
# # 6. Clean up the massive F16 file to free up Colab disk space
# rm /content/metrobot-f16.gguf
# 
# echo "Conversion complete! Refresh your file panel to see metrobot-Q4_K_M.gguf"

"""### Clear `unsloth_compiled_cache` and Retry GGUF Conversion"""

import shutil
import os
import sys

# Clear the unsloth_compiled_cache folder
cache_path = "/content/unsloth_compiled_cache"
if os.path.exists(cache_path):
    shutil.rmtree(cache_path)
    print(f"Cleared cache: {cache_path}")
else:
    print(f"Cache directory not found: {cache_path}")

# Add unsloth's internal llama.cpp directory to sys.path
# This is where unsloth's copied conversion scripts are likely located
# and where they expect to find the 'conversion' module.
unsloth_llama_cpp_path = "/root/.unsloth/llama.cpp"
if os.path.exists(unsloth_llama_cpp_path) and unsloth_llama_cpp_path not in sys.path:
    sys.path.insert(0, unsloth_llama_cpp_path)
    print(f"Added {unsloth_llama_cpp_path} to sys.path")
else:
    print(f"Path {unsloth_llama_cpp_path} not found or already in sys.path.")

# Retry the GGUF conversion
print("--- RETRYING GGUF CONVERSION AFTER CLEARING CACHE AND ADJUSTING PATH ---")
try:
    # Ensure environment variable is set for fast conversion if needed
    os.environ["UNSLOTH_GGUF_USE_FAST"] = "1"

    model.save_pretrained_gguf(
        "metrobot_gguf",
        tokenizer,
        quantization_method = "q4_k_m",
    )
    print("--- CONVERSION FINISHED SUCCESSFULLY ---")
    print("The .gguf file should now appear in the 'metrobot_gguf' folder in the left sidebar.")
except Exception as e:
    print(f"Conversion failed again after cache clear and path adjustment: {e}")
    print("Checking for any generated files:")
    !ls -R metrobot_gguf